wallpaper {
    monitor = DP-3
    path = /usr/share/backgrounds/desktop.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /usr/share/backgrounds/desktop.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /usr/share/backgrounds/desktop.jpg
    fit_mode = cover
}

splash = false

